// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Las migraciones necesitan una conexión directa (session mode, puerto
    // 5432): el pooler en transaction mode no soporta sentencias que abarcan
    // varias transacciones ni advisory locks. DATABASE_URL es del runtime y
    // apunta al pooler — ver el comentario en src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
